# Generated by Django 4.2.19 on 2025-02-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='tail_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
